<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BirthNoteSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('birth_notes')->insert([
            // Data Tahun 2024
            [
                'no_letter' => 1,
                'name' => "Patrick Star",
                'nik' => "3576447103910009",
                'no_dok_journey' => "1",
                'nationality' => "1",
                'no_wa' => "089876346764",
                'name_saksi' => "Plankton",
                'nik_saksi' => "3576447103910085",
                'nationality_saksi' => "1",
                'name_saksi2' => "Plankton",
                'nik_saksi2' => "3576447103910011",
                'nationality_saksi2' => "1",
                'name_dad' => "Euguene Star",
                'nik_dad' => "3576447103910012",
                'place_born_dad' => "USA",
                'date_born_dad' => "2002-04-03",
                'dad_job' => "Explorer",
                'address_dad' => "Bikini Bottom",
                'nationality_dad' => "2",
                'name_mom' => "Mama Star",
                'nik_mom' => "3576447103910013",
                'place_born_mom' => "Alaska",
                'date_born_mom' => "2002-03-02",
                'mom_job' => "Housewife",
                'address_mom' => "Bikini Bottom",
                'nationality_mom' => "1",
                'no_kk_anak' => "3576447103910014",
                'hub_keluarga' => "3",
                'name_child' => "Sicilian Star",
                'gender_child' => "1",
                'address_child' => "Bikini Bottom, 124 Conch Street", // Disesuaikan
                'place_birth_child' => "3",
                'place_birth_child2' => "Denpasar",
                'date_birth_child' => "2025-12-25",
                'hour_birth_child' => "23:59",
                'type_birth_child' => "5",
                'no_birth_child' => 2,
                'helper_birth' => "1",
                'weight_child' => "46",
                'height_child' => "164",
                'blood_type_child' => "A",
                'religion_child' => "4",
                'nationality_child' => "1",
                'disability' => "1",
                'year' => 2025,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [

                'no_letter' => 2,
                'name' => "Squidward Tentacles",
                'nik' => "3576447103910015",
                'no_dok_journey' => "2",
                'nationality' => "2",
                'no_wa' => "089876346752",
                'name_saksi' => "SpongeBob",
                'nik_saksi' => "3576447103910016",
                'nationality_saksi' => "1",
                'name_saksi2' => "Mr. Krabs",
                'nik_saksi2' => "3576447103910092",
                'nationality_saksi2' => "2",
                'name_dad' => "Papa Tentacles",
                'nik_dad' => "3576447103910018",
                'place_born_dad' => "Pacific Ocean",
                'date_born_dad' => "2000-06-15",
                'dad_job' => "Artist",
                'address_dad' => "Bikini Bottom",
                'nationality_dad' => "1",
                'name_mom' => "Mama Tentacles",
                'nik_mom' => "3576447103910019",
                'place_born_mom' => "Atlantic Ocean",
                'date_born_mom' => "2001-08-20",
                'mom_job' => "Musician",
                'address_mom' => "Bikini Bottom",
                'nationality_mom' => "2",
                'no_kk_anak' => "3576447103910020",
                'hub_keluarga' => "2",
                'name_child' => "Junior Tentacles",
                'gender_child' => "2",
                'address_child' => "Bikini Bottom, 122 Conch Street", // Disesuaikan
                'place_birth_child' => "5",
                'place_birth_child2' => "Surabaya",
                'date_birth_child' => "2024-01-15",
                'hour_birth_child' => "10:00",
                'type_birth_child' => "1",
                'no_birth_child' => 1,
                'helper_birth' => "2",
                'weight_child' => "50",
                'height_child' => "150",
                'blood_type_child' => "B",
                'religion_child' => "1",
                'nationality_child' => "1",
                'disability' => "0",
                'year' => 2024,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data Tahun 2025
            [
                'no_letter' => 1,
                'name' => "Mr. Krabs",
                'nik' => "3576447103910039",
                'no_dok_journey' => "1",
                'nationality' => "1",
                'no_wa' => "089823456789",
                'name_saksi' => "Squidward",
                'nik_saksi' => "3576447103910097",
                'nationality_saksi' => "1",
                'name_saksi2' => "Pearl",
                'nik_saksi2' => "3576447103910041",
                'nationality_saksi2' => "2",
                'name_dad' => "Captain Krabs",
                'nik_dad' => "3576447103910042",
                'place_born_dad' => "Krusty Krab",
                'date_born_dad' => "1995-03-03",
                'dad_job' => "Restaurant Owner",
                'address_dad' => "Bikini Bottom",
                'nationality_dad' => "1",
                'name_mom' => "Mrs. Krabs",
                'nik_mom' => "3576447103910043",
                'place_born_mom' => "Chum Bucket",
                'date_born_mom' => "1996-04-04",
                'mom_job' => "Businesswoman",
                'address_mom' => "Bikini Bottom",
                'nationality_mom' => "2",
                'no_kk_anak' => "3576447103910044",
                'hub_keluarga' => "2",
                'name_child' => "Money Krabs",
                'gender_child' => "2",
                'address_child' => "Bikini Bottom, 3541 Anchor Way", // Disesuaikan
                'place_birth_child' => "1",
                'place_birth_child2' => "Jakarta",
                'date_birth_child' => "2023-11-10",
                'hour_birth_child' => "12:30",
                'type_birth_child' => "2",
                'no_birth_child' => 2,
                'helper_birth' => "1",
                'weight_child' => "45",
                'height_child' => "155",
                'blood_type_child' => "O",
                'religion_child' => "3",
                'nationality_child' => "1",
                'disability' => "0",
                'year' => 2023,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data Tahun 2023
            [
                'no_letter' => 1,
                'name' => "Sandy Cheeks",
                'nik' => "3576447103910060",
                'no_dok_journey' => "1",
                'nationality' => "2",
                'no_wa' => "089845678901",
                'name_saksi' => "SpongeBob",
                'nik_saksi' => "3576447103910109",
                'nationality_saksi' => "1",
                'name_saksi2' => "Patrick",
                'nik_saksi2' => "3576447103910110",
                'nationality_saksi2' => "1",
                'name_dad' => "Mr. Cheeks",
                'nik_dad' => "3576447103910111",
                'place_born_dad' => "Texas",
                'date_born_dad' => "1990-08-15",
                'dad_job' => "Scientist",
                'address_dad' => "Texas",
                'nationality_dad' => "2",
                'name_mom' => "Mrs. Cheeks",
                'nik_mom' => "3576447103910064",
                'place_born_mom' => "Dallas",
                'date_born_mom' => "1991-09-20",
                'mom_job' => "Engineer",
                'address_mom' => "Texas",
                'nationality_mom' => "2",
                'no_kk_anak' => "3576447103910065",
                'hub_keluarga' => "1",
                'name_child' => "Junior Cheeks",
                'gender_child' => "1",
                'address_child' => "Bikini Bottom, Treedome", // Disesuaikan
                'place_birth_child' => "2",
                'place_birth_child2' => "Palembang",
                'date_birth_child' => "2023-06-15",
                'hour_birth_child' => "10:30",
                'type_birth_child' => "1",
                'no_birth_child' => 2,
                'helper_birth' => "1",
                'weight_child' => "49",
                'height_child' => "165",
                'blood_type_child' => "A",
                'religion_child' => "2",
                'nationality_child' => "2",
                'disability' => "0",
                'year' => 2021,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data Tahun 2025 (lagi)
            [
                'no_letter' => 2,
                'name' => "SpongeBob SquarePants",
                'nik' => "3576447103910072",
                'no_dok_journey' => "2",
                'nationality' => "1",
                'no_wa' => "089867890123",
                'name_saksi' => "Mr. Krabs",
                'nik_saksi' => "3576447103910121",
                'nationality_saksi' => "1",
                'name_saksi2' => "Squidward",
                'nik_saksi2' => "3576447103910074",
                'nationality_saksi2' => "2",
                'name_dad' => "Mr. SquarePants",
                'nik_dad' => "3576447103910075",
                'place_born_dad' => "Bikini Bottom",
                'date_born_dad' => "1989-05-05",
                'dad_job' => "Fry Cook",
                'address_dad' => "Bikini Bottom",
                'nationality_dad' => "1",
                'name_mom' => "Mrs. SquarePants",
                'nik_mom' => "3576447103910076",
                'place_born_mom' => "Jellyfish Fields",
                'date_born_mom' => "1990-06-06",
                'mom_job' => "Jellyfisher",
                'address_mom' => "Bikini Bottom",
                'nationality_mom' => "1",
                'no_kk_anak' => "3576447103910077",
                'hub_keluarga' => "3",
                'name_child' => "Spongy Jr",
                'gender_child' => "1",
                'address_child' => "Bikini Bottom, 124 Conch Street", // Disesuaikan
                'place_birth_child' => "5",
                'place_birth_child2' => "Manado",
                'date_birth_child' => "2025-04-20",
                'hour_birth_child' => "08:45",
                'type_birth_child' => "3",
                'no_birth_child' => 1,
                'helper_birth' => "3",
                'weight_child' => "60",
                'height_child' => "170",
                'blood_type_child' => "O",
                'religion_child' => "1",
                'nationality_child' => "1",
                'disability' => "5",
                'year' => 2025,
                "created_at" => "2025-04-20 08:45:00",
                "updated_at" => "2025-04-20 08:45:00"
            ]
        ]);
    }
}
