<?php

namespace Database\Seeders;

use App\Http\Services\LetterCounterService;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LetterFuelSeeder extends Seeder
{
    public function __construct(protected LetterCounterService $letterCounterService) {}
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('letter_fuels')->insert([

            // Year 2024
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Patrick Star",
                "nik" => "9837463567894873",
                "address" => "Bikini Bottom",
                "business_name" => "Krusty Star",
                "user_consumer_sector" => "Makanan",
                "business_type" => "F&B",
                "tool_type" => "Diesel",
                "tool_sum" => "10",
                "tool_power" => "8800",
                "tool_use" => "Sibel",
                "tool_time_used_hour" => "10",
                "tool_time_used_daily" => "7",
                "jbt_consumption" => "10",
                "tool_sum2" => "10",
                "volume_allocation" => "200",
                "pick_up_place" => "SPBU Sambit",
                "no_distributor" => "54.634.11",
                "address_distributor" => "DS BESUKI KC. SAMBIT",
                "purchasing_tools_used" => "Uang",
                "year" => 2024,
                "no_wa" => '081234567900', // Add no_wa column
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Eugene Krabs",
                "nik" => "9837463567894810",
                "address" => "Bikini Bottom",
                "business_name" => "Krusty Krabs",
                "user_consumer_sector" => "Makanan",
                "business_type" => "F&B",
                "tool_type" => "Diesel",
                "tool_sum" => "10",
                "tool_power" => "8800",
                "tool_use" => "Sibel",
                "tool_time_used_hour" => "10",
                "tool_time_used_daily" => "7",
                "jbt_consumption" => "10",
                "tool_sum2" => "10",
                "volume_allocation" => "200",
                "pick_up_place" => "SPBU Sambit",
                "no_distributor" => "54.634.11",
                "address_distributor" => "DS BESUKI KC. SAMBIT",
                "purchasing_tools_used" => "Uang",
                "year" => 2024,
                "no_wa" => '081234567900', // Add no_wa column
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Squidward Tentacles",
                "nik" => "9837463567894811",
                "address" => "Bikini Bottom",
                "business_name" => "Squid Music Studio",
                "user_consumer_sector" => "Hiburan",
                "business_type" => "Entertainment",
                "tool_type" => "Diesel",
                "tool_sum" => "8",
                "tool_power" => "7500",
                "tool_use" => "Generator",
                "tool_time_used_hour" => "8",
                "tool_time_used_daily" => "5",
                "jbt_consumption" => "8",
                "tool_sum2" => "8",
                "volume_allocation" => "150",
                "pick_up_place" => "SPBU Sambit",
                "no_distributor" => "54.634.11",
                "address_distributor" => "DS BESUKI KC. SAMBIT",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2024,
                "no_wa" => '081234567900', // Add no_wa column
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Sandy Cheeks",
                "nik" => "9837463567894812",
                "address" => "Bikini Bottom",
                "business_name" => "Science Lab",
                "user_consumer_sector" => "Penelitian",
                "business_type" => "Research",
                "tool_type" => "Diesel",
                "tool_sum" => "15",
                "tool_power" => "12000",
                "tool_use" => "Laboratory Equipment",
                "tool_time_used_hour" => "12",
                "tool_time_used_daily" => "6",
                "jbt_consumption" => "15",
                "tool_sum2" => "15",
                "volume_allocation" => "300",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "year" => 2024,
                "no_wa" => '081234567900', // Add no_wa column
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Plankton",
                "nik" => "9837463567894813",
                "address" => "Bikini Bottom",
                "business_name" => "Chum Bucket",
                "user_consumer_sector" => "Makanan",
                "business_type" => "F&B",
                "tool_type" => "Diesel",
                "tool_sum" => "5",
                "tool_power" => "5000",
                "tool_use" => "Kitchen Equipment",
                "tool_time_used_hour" => "6",
                "tool_time_used_daily" => "4",
                "jbt_consumption" => "5",
                "tool_sum2" => "5",
                "volume_allocation" => "100",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "year" => 2024,
                "no_wa" => '081234567900', // Add no_wa column
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],

            // Year 2025
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "SpongeBob SquarePants",
                "nik" => "9837463567894814",
                "address" => "Bikini Bottom",
                "business_name" => "Pineapple Kitchen",
                "user_consumer_sector" => "Makanan",
                "business_type" => "F&B",
                "tool_type" => "Diesel",
                "tool_sum" => "12",
                "tool_power" => "9000",
                "tool_use" => "Kitchen Equipment",
                "tool_time_used_hour" => "12",
                "tool_time_used_daily" => "7",
                "jbt_consumption" => "12",
                "tool_sum2" => "12",
                "volume_allocation" => "250",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2025,
                "created_at" => "2025-01-29 12:00:00",
                "updated_at" => "2025-01-29 12:00:00",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Larry the Lobster",
                "nik" => "9837463567894815",
                "address" => "Bikini Bottom",
                "business_name" => "Muscle Beach Gym",
                "user_consumer_sector" => "Olahraga",
                "business_type" => "Sports",
                "tool_type" => "Diesel",
                "tool_sum" => "20",
                "tool_power" => "15000",
                "tool_use" => "Gym Equipment",
                "tool_time_used_hour" => "16",
                "tool_time_used_daily" => "7",
                "jbt_consumption" => "20",
                "tool_sum2" => "20",
                "volume_allocation" => "400",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2025,
                "created_at" => "2025-01-29 12:00:00",
                "updated_at" => "2025-01-29 12:00:00",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Mrs. Puff",
                "nik" => "9837463567894816",
                "address" => "Bikini Bottom",
                "business_name" => "Boating School",
                "user_consumer_sector" => "Pendidikan",
                "business_type" => "Education",
                "tool_type" => "Diesel",
                "tool_sum" => "15",
                "tool_power" => "10000",
                "tool_use" => "Training Equipment",
                "tool_time_used_hour" => "10",
                "tool_time_used_daily" => "6",
                "jbt_consumption" => "15",
                "tool_sum2" => "15",
                "volume_allocation" => "300",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2025,
                "created_at" => "2025-01-29 12:00:00",
                "updated_at" => "2025-01-29 12:00:00",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Pearl Krabs",
                "nik" => "9837463567894817",
                "address" => "Bikini Bottom",
                "business_name" => "Pearl's Fashion",
                "user_consumer_sector" => "Fashion",
                "business_type" => "Retail",
                "tool_type" => "Diesel",
                "tool_sum" => "8",
                "tool_power" => "6000",
                "tool_use" => "Store Equipment",
                "tool_time_used_hour" => "12",
                "tool_time_used_daily" => "7",
                "jbt_consumption" => "8",
                "tool_sum2" => "8",
                "volume_allocation" => "160",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2025,
                "created_at" => "2025-01-29 12:00:00",
                "updated_at" => "2025-01-29 12:00:00",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Flying Dutchman",
                "nik" => "9837463567894818",
                "address" => "Bikini Bottom",
                "business_name" => "Ghost Ship Tours",
                "user_consumer_sector" => "Pariwisata",
                "business_type" => "Tourism",
                "tool_type" => "Diesel",
                "tool_sum" => "25",
                "tool_power" => "20000",
                "tool_use" => "Ship Equipment",
                "tool_time_used_hour" => "24",
                "tool_time_used_daily" => "7",
                "jbt_consumption" => "25",
                "tool_sum2" => "25",
                "volume_allocation" => "500",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2025,
                "created_at" => "2025-01-29 12:00:00",
                "updated_at" => "2025-01-29 12:00:00",
            ],
            // 2023 Data
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2023),
                "name" => "Mermaid Man",
                "nik" => "9837463567894819",
                "address" => "Bikini Bottom",
                "business_name" => "Superhero Training Center",
                "user_consumer_sector" => "Pendidikan",
                "business_type" => "Education",
                "tool_type" => "Diesel",
                "tool_sum" => "15",
                "tool_power" => "12000",
                "tool_use" => "Training Equipment",
                "tool_time_used_hour" => "12",
                "tool_time_used_daily" => "6",
                "jbt_consumption" => "15",
                "tool_sum2" => "15",
                "volume_allocation" => "300",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2023,
                "created_at" => "2023-06-15 09:30:00",
                "updated_at" => "2023-06-15 09:30:00",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2023),
                "name" => "Barnacle Boy",
                "nik" => "9837463567894820",
                "address" => "Bikini Bottom",
                "business_name" => "Senior Hero Society",
                "user_consumer_sector" => "Hiburan",
                "business_type" => "Entertainment",
                "tool_type" => "Diesel",
                "tool_sum" => "10",
                "tool_power" => "9000",
                "tool_use" => "Recreation Equipment",
                "tool_time_used_hour" => "8",
                "tool_time_used_daily" => "5",
                "jbt_consumption" => "10",
                "tool_sum2" => "10",
                "volume_allocation" => "200",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2023,
                "created_at" => "2023-06-15 09:30:00",
                "updated_at" => "2023-06-15 09:30:00",
            ],

            // 2022 Data
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2022),
                "name" => "Karen Plankton",
                "nik" => "9837463567894821",
                "address" => "Bikini Bottom",
                "business_name" => "Digital Solutions",
                "user_consumer_sector" => "Teknologi",
                "business_type" => "Technology",
                "tool_type" => "Diesel",
                "tool_sum" => "20",
                "tool_power" => "15000",
                "tool_use" => "Computer Servers",
                "tool_time_used_hour" => "24",
                "tool_time_used_daily" => "7",
                "jbt_consumption" => "20",
                "tool_sum2" => "20",
                "volume_allocation" => "400",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2022,
                "created_at" => "2022-03-20 14:45:00",
                "updated_at" => "2022-03-20 14:45:00",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2022),
                "name" => "Fred the Fish",
                "nik" => "9837463567894822",
                "address" => "Bikini Bottom",
                "business_name" => "Fish Market Fresh",
                "user_consumer_sector" => "Retail",
                "business_type" => "Market",
                "tool_type" => "Diesel",
                "tool_sum" => "12",
                "tool_power" => "10000",
                "tool_use" => "Cold Storage",
                "tool_time_used_hour" => "24",
                "tool_time_used_daily" => "7",
                "jbt_consumption" => "12",
                "tool_sum2" => "12",
                "volume_allocation" => "250",
                "pick_up_place" => "SPBU Nailan",
                "no_distributor" => "54.634.12",
                "address_distributor" => "JL. RAYA DS.BALONG-SLAHUNG",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2022,
                "created_at" => "2022-03-20 14:45:00",
                "updated_at" => "2022-03-20 14:45:00",
            ],

            // 2021 Data
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2021),
                "name" => "Harold SquarePants",
                "nik" => "9837463567894823",
                "address" => "Bikini Bottom",
                "business_name" => "Retirement Paradise",
                "user_consumer_sector" => "Rekreasi",
                "business_type" => "Recreation",
                "tool_type" => "Diesel",
                "tool_sum" => "8",
                "tool_power" => "7000",
                "tool_use" => "Leisure Equipment",
                "tool_time_used_hour" => "10",
                "tool_time_used_daily" => "5",
                "jbt_consumption" => "8",
                "tool_sum2" => "8",
                "volume_allocation" => "160",
                "pick_up_place" => "SPBU Sambit",
                "no_distributor" => "54.634.11",
                "address_distributor" => "DS BESUKI KC. SAMBIT",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2021,
                "created_at" => "2021-11-05 10:15:00",
                "updated_at" => "2021-11-05 10:15:00",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2021),
                "name" => "Margaret SquarePants",
                "nik" => "9837463567894824",
                "address" => "Bikini Bottom",
                "business_name" => "Cookie Factory",
                "user_consumer_sector" => "Makanan",
                "business_type" => "F&B",
                "tool_type" => "Diesel",
                "tool_sum" => "10",
                "tool_power" => "8500",
                "tool_use" => "Baking Equipment",
                "tool_time_used_hour" => "12",
                "tool_time_used_daily" => "6",
                "jbt_consumption" => "10",
                "tool_sum2" => "10",
                "volume_allocation" => "200",
                "pick_up_place" => "SPBU Sambit",
                "no_distributor" => "54.634.11",
                "address_distributor" => "DS BESUKI KC. SAMBIT",
                "purchasing_tools_used" => "Uang",
                "no_wa" => '081234567900', // Add no_wa column
                "year" => 2021,
                "created_at" => "2021-11-05 10:15:00",
                "updated_at" => "2021-11-05 10:15:00",
            ]
        ]);
    }
}
