<?php

namespace Database\Seeders;

use App\Http\Services\LetterCounterService;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LetterIncapacitiesSeeder extends Seeder
{
    public function __construct(protected LetterCounterService $letterCounterService) {}
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('letter_incapacities')->insert([
            // Year 2021
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2021),
                "name" => "King Neptune",
                "tgl_lahir" => '1970-07-01',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'S3',
                "job" => 'Raja',
                "marriage" => 'Sudah Kawin',
                "nik" => '2317391729321940',
                "religion" => 'Islam',
                "address" => 'Bikini Bottom',
                "name_child" => 'Mindy',
                "tgl_lahir_child" => '2002-07-05',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Perempuan',
                "education_child" => 'SMP',
                "address_child" => 'Wringinanom',
                "year" => 2021,
                "created_at" => "2021-07-15 10:30:22",
                "updated_at" => "2021-07-15 10:30:22",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2021),
                "name" => "Man Ray",
                "tgl_lahir" => '1985-08-15',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Villain',
                "marriage" => 'Belum Kawin',
                "nik" => '2317391729321941',
                "religion" => 'Kristen',
                "address" => 'Bikini Bottom',
                "name_child" => 'Dennis',
                "tgl_lahir_child" => '2002-08-20',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2021,
                "created_at" => "2021-08-25 14:20:45",
                "updated_at" => "2021-08-25 14:20:45",
            ],

            // Year 2022
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2022),
                "name" => "Grandma SquarePants",
                "tgl_lahir" => '1945-03-03',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Perempuan',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Pensiunan',
                "marriage" => 'Janda',
                "nik" => '2317391729321942',
                "religion" => 'Islam',
                "address" => 'Bikini Bottom',
                "name_child" => 'Stanley',
                "tgl_lahir_child" => '2003-03-10',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMP',
                "address_child" => 'Wringinanom',
                "year" => 2022,
                "created_at" => "2022-03-20 09:15:33",
                "updated_at" => "2022-03-20 09:15:33",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2022),
                "name" => "Squilliam Fancyson",
                "tgl_lahir" => '1985-04-25',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'S2',
                "job" => 'Pengusaha',
                "marriage" => 'Sudah Kawin',
                "nik" => '2317391729321943',
                "religion" => 'Kristen',
                "address" => 'Bikini Bottom',
                "name_child" => 'Monroe',
                "tgl_lahir_child" => '2003-04-15',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2022,
                "created_at" => "2022-04-30 16:45:50",
                "updated_at" => "2022-04-30 16:45:50",
            ],

            // Year 2023
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2023),
                "name" => "Harold SquarePants",
                "tgl_lahir" => '1965-09-10',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Wiraswasta',
                "marriage" => 'Sudah Kawin',
                "nik" => '2317391729321944',
                "religion" => 'Islam',
                "address" => 'Bikini Bottom',
                "name_child" => 'BlackJack',
                "tgl_lahir_child" => '2004-09-05',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMP',
                "address_child" => 'Wringinanom',
                "year" => 2023,
                "created_at" => "2023-09-15 11:25:17",
                "updated_at" => "2023-09-15 11:25:17",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2023),
                "name" => "Margaret SquarePants",
                "tgl_lahir" => '1967-10-20',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Perempuan',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Ibu Rumah Tangga',
                "marriage" => 'Sudah Kawin',
                "nik" => '2317391729321945',
                "religion" => 'Islam',
                "address" => 'Bikini Bottom',
                "name_child" => 'Todd',
                "tgl_lahir_child" => '2004-10-15',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2023,
                "created_at" => "2023-10-25 13:40:55",
                "updated_at" => "2023-10-25 13:40:55",
            ],

            // Year 2024
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Euguene Krabs",
                "tgl_lahir" => '1988-08-28',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'SMA',
                "job" => 'Manager',
                "marriage" => 'Duda',
                "nik" => '2317391729321931',
                "religion" => 'Islam',
                "address" => 'Bikini Bottom',
                "name_child" => 'Spongebob',
                "tgl_lahir_child" => '2003-09-20',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2024,
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Patrick Star",
                "tgl_lahir" => '1988-08-28',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'SMA',
                "job" => 'Manager',
                "marriage" => 'Duda',
                "nik" => '2317391729321931',
                "religion" => 'Islam',
                "address" => 'Bikini Bottom',
                "name_child" => 'Spongebob',
                "tgl_lahir_child" => '2003-09-20',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2024,
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Squidward Tentacles",
                "tgl_lahir" => '1985-10-15',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Kasir',
                "marriage" => 'Belum Kawin',
                "nik" => '2317391729321933',
                "religion" => 'Kristen',
                "address" => 'Bikini Bottom',
                "name_child" => 'Pearl',
                "tgl_lahir_child" => '2004-06-05',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Perempuan',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2024,
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Sheldon Plankton",
                "tgl_lahir" => '1989-11-30',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'S2',
                "job" => 'Pengusaha',
                "marriage" => 'Sudah Kawin',
                "nik" => '2317391729321934',
                "religion" => 'Islam',
                "address" => 'Bikini Bottom',
                "name_child" => 'Karen',
                "tgl_lahir_child" => '2004-12-12',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Perempuan',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2024,
                "created_at" => "2024-09-26 01:21:32",
                "updated_at" => "2024-09-26 01:21:32",
            ],

            // Year 2025
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Mrs Puff",
                "tgl_lahir" => '1980-01-03',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Perempuan',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Guru',
                "marriage" => 'Sudah Kawin',
                "nik" => '2317391729321935',
                "religion" => 'Kristen',
                "address" => 'Bikini Bottom',
                "name_child" => 'Larry',
                "tgl_lahir_child" => '2005-01-08',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2025,
                "created_at" => "2025-01-15 09:45:22",
                "updated_at" => "2025-01-15 09:45:22",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Sandy Cheeks",
                "tgl_lahir" => '1982-11-17',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Perempuan',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Ilmuwan',
                "marriage" => 'Sudah Kawin',
                "nik" => '2317391729321936',
                "religion" => 'Islam',
                "address" => 'Bikini Bottom',
                "name_child" => 'Pearl',
                "tgl_lahir_child" => '2005-06-22',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Perempuan',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2025,
                "created_at" => "2025-01-15 10:15:33",
                "updated_at" => "2025-01-15 10:15:33",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Eugene Krabs",
                "tgl_lahir" => '1975-03-30',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Pengusaha',
                "marriage" => 'Duda',
                "nik" => '2317391729321937',
                "religion" => 'Hindu',
                "address" => 'Bikini Bottom',
                "name_child" => 'Plankton',
                "tgl_lahir_child" => '2005-08-10',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2025,
                "created_at" => "2025-01-15 10:45:45",
                "updated_at" => "2025-01-15 10:45:45",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Patrick Star",
                "tgl_lahir" => '1981-02-26',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Laki-laki',
                "nationality" => 'WNA',
                "education" => 'S1',
                "job" => 'Seniman',
                "marriage" => 'Sudah Kawin',
                "nik" => '2317391729321938',
                "religion" => 'Buddha',
                "address" => 'Bikini Bottom',
                "name_child" => 'Squidward',
                "tgl_lahir_child" => '2006-01-05',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2025,
                "created_at" => "2025-01-15 11:20:12",
                "updated_at" => "2025-01-15 11:20:12",
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Karen Plankton",
                "tgl_lahir" => '1983-09-08',
                "tempat_lahir" => 'Bikini Bottom',
                "gender" => 'Perempuan',
                "nationality" => 'WNA',
                "education" => 'S2',
                "job" => 'Programmer',
                "marriage" => 'Janda',
                "nik" => '2317391729321939',
                "religion" => 'Katolik',
                "address" => 'Bikini Bottom',
                "name_child" => 'Larry',
                "tgl_lahir_child" => '2006-04-18',
                "tempat_lahir_child" => 'Ponorogo',
                "gender_child" => 'Laki-laki',
                "education_child" => 'SMA',
                "address_child" => 'Wringinanom',
                "year" => 2025,
                "created_at" => "2025-01-15 12:05:55",
                "updated_at" => "2025-01-15 12:05:55",
            ],
        ]);
    }
}
