<?php

namespace Database\Seeders;

use App\Http\Services\LetterCounterService;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LetterDeathSeeder extends Seeder
{
    public function __construct(protected LetterCounterService $letterCounterService) {}

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('letter_deaths')->insert([
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Konan",
                "place_birth" => "Amegakure",
                "date_birth" => "1984-02-23",
                "nik" => "9837463567894873",
                "date_death" => "2010-12-03",
                "hour_death" => "09:30",
                "cause_death" => "Dibunuh Obito",
                "order_child" => 1,
                "witness" => "Nagato",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "year" => 2025,
                "no_wa" => '081234567900',
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Jiraiya",
                "place_birth" => "Konohagakure",
                "date_birth" => "1965-11-11",
                "nik" => "9837463567894873",
                "date_death" => "2010-12-03",
                "hour_death" => "09:30",
                "cause_death" => "Dibunuh Pain",
                "order_child" => 2,
                "witness" => "Naruto Uzumaki",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2025,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Minato Namikaze",
                "place_birth" => "Konohagakure",
                "date_birth" => "1980-01-25",
                "nik" => "9837463567894874",
                "date_death" => "1999-10-10",
                "hour_death" => "23:00",
                "cause_death" => "Melindungi Konoha dari Kurama",
                "order_child" => 1,
                "witness" => "Kushina Uzumaki",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2025,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Itachi Uchiha",
                "place_birth" => "Konohagakure",
                "date_birth" => "1988-06-09",
                "nik" => "9837463567894875",
                "date_death" => "2014-06-15",
                "hour_death" => "17:30",
                "cause_death" => "Pertarungan melawan Sasuke",
                "order_child" => 1,
                "witness" => "Sasuke Uchiha",
                "mom_name" => "Mikoto Uchiha",
                "dad_name" => "Fugaku Uchiha",
                "no_wa" => '081234567900',
                "year" => 2025,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Neji Hyuga",
                "place_birth" => "Konohagakure",
                "date_birth" => "1992-07-03",
                "nik" => "9837463567894876",
                "date_death" => "2016-12-14",
                "hour_death" => "12:00",
                "cause_death" => "Melindungi Hinata dan Naruto",
                "order_child" => 1,
                "witness" => "Hinata Hyuga",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Hizashi Hyuga",
                "no_wa" => '081234567900',
                "year" => 2025,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Madara Uchiha",
                "place_birth" => "Konohagakure",
                "date_birth" => "1899-01-01",
                "nik" => "9837463567894877",
                "date_death" => "2018-02-29",
                "hour_death" => "20:00",
                "cause_death" => "Dikhianati Zetsu Hitam",
                "order_child" => 1,
                "witness" => "Hashirama Senju",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2025,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2025),
                "name" => "Obito Uchiha",
                "place_birth" => "Konohagakure",
                "date_birth" => "1986-02-10",
                "nik" => "9837463567894878",
                "date_death" => "2019-07-30",
                "hour_death" => "15:00",
                "cause_death" => "Berkorban untuk Naruto dan Sasuke",
                "order_child" => 1,
                "witness" => "Kakashi Hatake",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2025,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Hiruzen Sarutobi",
                "place_birth" => "Konohagakure",
                "date_birth" => "1929-02-08",
                "nik" => "9837463567894879",
                "date_death" => "2002-09-27",
                "hour_death" => "18:00",
                "cause_death" => "Melawan Orochimaru",
                "order_child" => 1,
                "witness" => "Orochimaru",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2024,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Danzo Shimura",
                "place_birth" => "Konohagakure",
                "date_birth" => "1930-01-01",
                "nik" => "9837463567894880",
                "date_death" => "2011-01-12",
                "hour_death" => "14:00",
                "cause_death" => "Dibunuh Sasuke",
                "order_child" => 1,
                "witness" => "Sasuke Uchiha",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2024,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Asuma Sarutobi",
                "place_birth" => "Konohagakure",
                "date_birth" => "1966-10-18",
                "nik" => "9837463567894881",
                "date_death" => "2013-11-03",
                "hour_death" => "11:00",
                "cause_death" => "Dibunuh Hidan",
                "order_child" => 1,
                "witness" => "Shikamaru Nara",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Hiruzen Sarutobi",
                "no_wa" => '081234567900',
                "year" => 2024,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Kushina Uzumaki",
                "place_birth" => "Uzugakure",
                "date_birth" => "1978-07-10",
                "nik" => "9837463567894882",
                "date_death" => "1999-10-10",
                "hour_death" => "23:05",
                "cause_death" => "Melindungi Naruto",
                "order_child" => 1,
                "witness" => "Minato Namikaze",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2024,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2024),
                "name" => "Zabuza Momochi",
                "place_birth" => "Kirigakure",
                "date_birth" => "1974-08-15",
                "nik" => "9837463567894883",
                "date_death" => "2010-08-15",
                "hour_death" => "16:00",
                "cause_death" => "Dibunuh oleh pasukan Gato",
                "order_child" => 1,
                "witness" => "Haku",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2024,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2023),
                "name" => "Madara Uchiha",
                "place_birth" => "Konohagakure",
                "date_birth" => "1899-01-01",
                "nik" => "9837463567894890",
                "date_death" => "2018-12-24",
                "hour_death" => "21:30",
                "cause_death" => "Dibunuh oleh Zetsu",
                "order_child" => 1,
                "witness" => "Hashirama Senju",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2023,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2023),
                "name" => "Obito Uchiha",
                "place_birth" => "Konohagakure",
                "date_birth" => "1986-02-10",
                "nik" => "9837463567894891",
                "date_death" => "2019-05-10",
                "hour_death" => "15:45",
                "cause_death" => "Dibunuh oleh Kaguya",
                "order_child" => 1,
                "witness" => "Kakashi Hatake",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2023,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2022),
                "name" => "Itachi Uchiha",
                "place_birth" => "Konohagakure",
                "date_birth" => "1988-06-09",
                "nik" => "9837463567894892",
                "date_death" => "2017-06-12",
                "hour_death" => "17:00",
                "cause_death" => "Bertarung dengan Sasuke",
                "order_child" => 1,
                "witness" => "Sasuke Uchiha",
                "mom_name" => "Mikoto Uchiha",
                "dad_name" => "Fugaku Uchiha",
                "no_wa" => '081234567900',
                "year" => 2022,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2022),
                "name" => "Neji Hyuga",
                "place_birth" => "Konohagakure",
                "date_birth" => "1992-07-03",
                "nik" => "9837463567894893",
                "date_death" => "2016-08-23",
                "hour_death" => "14:30",
                "cause_death" => "Melindungi Hinata dan Naruto",
                "order_child" => 1,
                "witness" => "Hinata Hyuga",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Hizashi Hyuga",
                "no_wa" => '081234567900',
                "year" => 2022,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2021),
                "name" => "Haku",
                "place_birth" => "Tanah Air",
                "date_birth" => "1990-01-01",
                "nik" => "9837463567894894",
                "date_death" => "2015-03-30",
                "hour_death" => "08:15",
                "cause_death" => "Dibunuh oleh Kakashi",
                "order_child" => 1,
                "witness" => "Zabuza Momochi",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2021,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "no_letter" => $this->letterCounterService->getNextLetterNumber(2021),
                "name" => "Sakumo Hatake",
                "place_birth" => "Konohagakure",
                "date_birth" => "1950-01-01",
                "nik" => "9837463567894895",
                "date_death" => "2014-02-11",
                "hour_death" => "22:00",
                "cause_death" => "Bunuh diri karena kehilangan kehormatan",
                "order_child" => 1,
                "witness" => "Tidak ada",
                "mom_name" => "Tidak diketahui",
                "dad_name" => "Tidak diketahui",
                "no_wa" => '081234567900',
                "year" => 2021,
                "created_at" => now(),
                "updated_at" => now(),
            ]
        ]);
    }
}
